Repository likeyeon/Gendata, pull requests merged in 2023-08, with the labels that each got.

#4 chore: scss 공통 스타일 적용
  src/App.css
  src/App.js
  src/index.css
  src/index.js
  src/pages/about/About.js
  src/pages/home/Home.js
  src/style/_colors.scss
  src/style/_util.scss
  src/style/reset.css
  src/style/style.scss
Labels: 🛠 Fix, ⚙️ Setting

#24 Gnb 공통 컴포넌트 제작, FontAwsome 패키지 설치
  package.json
  src/assets/gnb/logo_dark.png
  src/assets/gnb/logo_white.png
  src/components/gnb/Gnb.js
  src/components/gnb/Gnb.module.scss
  src/index.js
  src/pages/ai-development/AiDevelopment.js
  src/style/_colors.scss
  yarn.lock
Labels: 🛠 Fix, ✨ Feat, ⚙️ Chore, 🎨 Design

#36 Fix: Gnb 메뉴 개수 수정
  src/components/gnb/Gnb.js
Labels: 🛠 Fix

#20 Feat: Add common component ContactButton
  src/assets/contactButtonBackground.png
  src/components/common/typo/Typo.js
  src/components/common/typo/Typo.module.scss
  src/components/contact-button/ContactButton.js
  src/components/contact-button/ContactButton.module.scss
Labels: 🌎 deploy, ✨ Feat, 🎨 Design

#13 [1M20M] Feat: Add AiDevelopment page Title component
  src/components/common/typo/Typo.js
  src/components/common/typo/Typo.module.scss
  src/components/title/Title.js
  src/components/title/Title.module.scss
  src/pages/ai-development/AiDevelopment.js
  src/pages/ai-development/AiDevelopment.module.scss
  src/pages/ai-development/components/AiDevlopmentTitle.js
  src/pages/ai-development/components/AiDevlopmentTitle.module.scss
Labels: 🚜 Refactor, ✨ Feat, 🎨 Design

#19 [1M2H} Feat: Common component 'Strength(강점)' 만들기
  src/components/strength/Strength.js
  src/components/strength/Strength.module.scss
  src/pages/ai-development/AiDevelopment.js
Labels: 🙋‍♀️ Question, ✨ Feat

#14 [1M20M]Feat: Add AiDevelopment page application component
  src/pages/ai-development/AiDevelopment.js
  src/pages/ai-development/components/AiDevelopmentApplication.js
  src/pages/ai-development/components/AiDevelopmentApplication.module.scss
Labels: 🚜 Refactor, ✨ Feat, 🎨 Design

#15 [1M30M] Feature/heekyung/ai develop/recommend
  src/pages/ai-development/AiDevelopment.js
  src/pages/ai-development/components/AiDevelopmentRecommend.js
  src/pages/ai-development/components/AiDevelopmentRecommend.module.scss
Labels: ✨ Feat

#16 [1M40M] Feat: Add AiDevelopment page Case component
  src/pages/ai-development/AiDevelopment.js
  src/pages/ai-development/components/AiDevelopmentCase.js
  src/pages/ai-development/components/AiDevelopmentCase.module.scss
Labels: ✨ Feat

#46 Feat: Form 공통 컴포넌트, 문의하기 section1 개발
  src/components/form/FormButton.js
  src/components/form/FormButton.module.scss
  src/components/form/InputField.js
  src/components/form/InputField.module.scss
  src/components/form/Label.js
  src/components/form/Label.module.scss
  src/components/form/Modal.js
  src/components/form/Modal.module.scss
  src/components/form/PrivacyPolicyCheck.js
  src/components/form/PrivacyPolicyCheck.module.scss
  src/components/form/SelectField.js
  src/components/form/SelectField.module.scss
  src/components/form/TextareaField.js
  src/components/form/TextareaField.module.scss
  src/components/gnb/Gnb.js
  src/components/inside/Inside.js
  src/components/inside/Inside.module.scss
  src/index.js
  src/pages/contact/Contact.js
  src/pages/contact/Contact.module.scss
  src/pages/contact/components/ContactTitle.js
  src/pages/contact/components/Form.js
  src/pages/contact/components/Form.module.scss
  src/pages/contact/components/TextWidget.js
  src/pages/contact/components/TextWidget.module.scss
Labels: 🚜 Refactor, ✨ Feat

#42 Chore: add mockData, page(11/30)
  src/Mock/newsBoard.json
  src/assets/newBoard/1.png
  src/assets/newBoard/10.png
  src/assets/newBoard/11.png
  src/assets/newBoard/4.png
  src/assets/newBoard/6.png
  src/assets/newBoard/7.png
  src/assets/newBoard/8.png
  src/assets/newBoard/9.png
Labels: ⚙️ Chore

#49 Fix: 전체 레이아웃, 라우터 설정 및 Gnb css 디테일 수정
  src/App.js
  src/components/gnb/Gnb.js
  src/components/gnb/Gnb.module.scss
  src/index.js
  src/style/style.scss
Labels: 🛠 Fix

#54 Feature/kyungjin/tab
  src/components/common/button-type/ButtonType.js
  src/components/common/button-type/ButtonType.module.scss
  src/index.js
  src/pages/service-labeling/components/common/components/tab/Tab.module.scss
  src/pages/service-labeling/components/common/components/tab/TabContent.js
  src/pages/service-labeling/components/common/components/tab/TabContent.module.scss
  src/style/_colors.scss
Labels: 🚜 Refactor

#52 교육페이지 전체 컴포넌트 및 미디어쿼리 적용
  src/pages/ai-development/components/AiDevelopmentApplication.module.scss
  src/pages/ai-development/components/AiDevelopmentCase.module.scss
  src/pages/education/Education.js
  src/pages/education/components/Contact.js
  src/pages/education/components/educationIntro/EducationIntro.js
  src/pages/education/components/educationIntro/EducationIntro.module.scss
  src/pages/education/components/educationReview/EducationReview.js
  src/pages/education/components/educationReview/EducationReview.module.scss
  src/pages/education/components/educationSystem/EducationSystem.js
  src/pages/education/components/educationSystem/EducationSystem.module.scss
  src/pages/education/components/educationTitle/EducationTitle.js
  src/pages/education/components/educationTitle/EducationTitle.module.scss
Labels: ✨ Feat, 🎨 Design

#56 소식 게시판 mock data 만들기
  src/Mock/newsBoard.json
Labels: ✨ Feat

#57 Feat: Naver Maps API 지도 구현 및 문의하기 페이지 개발
  .gitignore
  package.json
  src/pages/contact/Contact.js
  src/pages/contact/Contact.module.scss
  src/pages/contact/components/CompanyInfo.js
  src/pages/contact/components/CompanyInfo.module.scss
  src/pages/contact/components/CompanyMap.js
  src/pages/contact/components/Form.js
  src/pages/contact/components/NaverMapApi.js
  src/pages/contact/components/NaverMapApi.module.scss
  src/pages/contact/components/Section2.js
  src/pages/contact/components/Section2.module.scss
  yarn.lock
Labels: ✨ Feat, ⚙️ Chore

#60 Feat: 정부지원사업 페이지 개발
  src/assets/government/aiVoucher.png
  src/assets/government/dataVoucher.png
  src/assets/government/governmentBanner.png
  src/assets/government/governmentBanner_tablet.png
  src/assets/government/niaAiData.png
  src/assets/government/rndApply.png
  src/components/form/PrivacyPolicyCheck.js
  src/components/form/PrivacyPolicyCheck.module.scss
  src/components/form/TextareaField.js
  src/components/form/TextareaField.module.scss
  src/index.js
  src/pages/government/Government.js
  src/pages/government/components/GovernmentTitle.js
  src/pages/government/components/governmentContact/Form.js
  src/pages/government/components/governmentContact/Form.module.scss
  src/pages/government/components/governmentContact/GovernmentContact.js
  src/pages/government/components/governmentContact/GovernmentContact.module.scss
  src/pages/government/components/governmentSupport/GovernmentProject.js
  src/pages/government/components/governmentSupport/GovernmentProject.module.scss
  src/pages/government/components/governmentSupport/GovernmentSupport.js
  src/pages/government/components/governmentSupport/GovernmentSupport.module.scss
  src/pages/government/components/governmentSupport/GovernmentSupportBanner.js
  src/pages/government/components/governmentSupport/GovernmentSupportBanner.module.scss
Labels: 🛠 Fix, ✨ Feat, ⚙️ Chore

#65 Feat : 원천데이터 수집 페이지 구현
  src/assets/data-building/data_collection1.png
  src/assets/data-building/data_collection2.png
  src/assets/data-building/data_collection3.png
  src/assets/data-building/data_collection4.png
  src/assets/data-building/data_collection5.png
  src/assets/data-building/data_collection_equip1.png
  src/assets/data-building/data_collection_equip2.png
  src/assets/data-building/data_collection_equip3.png
  src/assets/data-building/data_collection_equip4.png
  src/index.js
  src/pages/service-labeling/DataCollection.js
  src/pages/service-labeling/components/DataCollectionDescription.js
  src/pages/service-labeling/components/DataCollectionDescription.module.scss
  src/pages/service-labeling/components/DataCollectionEquipment.js
  src/pages/service-labeling/components/DataCollectionEquipment.module.scss
  src/pages/service-labeling/components/DataCollectionTitle.js
  src/style/style.scss
Labels: ✨ Feat

#66 Feat : 품질 및 보안 인하우스 작업 프로세스 섹션 구현
  src/assets/data-building/inhouse_manage_icon1.png
  src/assets/data-building/inhouse_manage_icon2.png
  src/assets/data-building/inhouse_manage_icon3.png
  src/assets/data-building/inhouse_manage_icon4.png
  src/assets/data-building/inhouse_manage_icon5.png
  src/assets/data-building/inhouse_prevent1.png
  src/assets/data-building/inhouse_prevent2.png
  src/assets/data-building/inhouse_prevent3.png
  src/assets/data-building/inhouse_prevent4.png
  src/assets/data-building/inhouse_work_icon1.png
  src/assets/data-building/inhouse_work_icon2.png
  src/assets/data-building/inhouse_work_icon3.png
  src/assets/data-building/inhouse_work_icon4.png
  src/assets/data-building/inhouse_work_icon5.png
  src/index.js
  src/pages/service-labeling/InHouseOperation.js
  src/pages/service-labeling/components/InHouseTitle.js
  src/pages/service-labeling/components/InHouseWorkProcess.js
  src/pages/service-labeling/components/InHouseWorkProcess.module.scss
  src/style/_colors.scss
Labels: ✨ Feat

#68 Feat : 품질 및 보안 사전 차단 섹션 구현
  src/pages/service-labeling/InHouseOperation.js
  src/pages/service-labeling/components/InHousePrevention.js
  src/pages/service-labeling/components/InHousePrevention.module.scss
Labels: ✨ Feat

#69 Feat : 품질 및 보안 관리 프로세스 섹션 구현
  src/assets/data-building/inhouse_manage_title.png
  src/pages/service-labeling/InHouseOperation.js
  src/pages/service-labeling/components/InHouseManage.js
  src/pages/service-labeling/components/InHouseManage.module.scss
  src/style/_colors.scss
Labels: ✨ Feat

#62 Feature/heekyung/news/board
  package.json
  src/Mock/newsBoard.json
  src/index.js
  src/pages/news/News.js
  src/pages/news/components/newsBoard/NewsBoard.js
  src/pages/news/components/newsBoard/NewsBoard.module.scss
  src/pages/news/components/newsBoard/components/NewsBoardList.js
  src/pages/news/components/newsBoard/components/NewsBoardList.module.scss
  src/pages/news/components/newsBoard/components/getBoardData.js
  src/pages/news/components/newsBoardTitle/NewsBoardTitle.js
  src/pages/news/components/newsBoardTitle/NewsBoardTitle.module.scss
  src/pages/newsContents/NewsContents.js
  src/pages/newsContents/NewsContents.module.scss
Labels: ✨ Feat, 🎨 Design

#71 Design: 헤더 css 수정
  src/components/gnb/Gnb.js
  src/components/gnb/Gnb.module.scss
  src/pages/main/components/buildingData/BuildingData.js
  src/style/style.scss
Labels: 🎨 Design

#73 Design/heekyung
  src/assets/ai-development/minCard1.png
  src/assets/ai-development/minCard2.png
  src/components/strength/Strength.js
  src/components/strength/Strength.module.scss
  src/components/title/Title.js
  src/components/title/Title.module.scss
  src/pages/ai-development/components/AiDevelopmentApplication.js
  src/pages/ai-development/components/AiDevelopmentApplication.module.scss
  src/pages/ai-development/components/AiDevelopmentRecommend.module.scss
  src/pages/ai-development/components/AiDevlopmentTitle.js
  src/pages/ai-development/components/AiDevlopmentTitle.module.scss
  src/pages/education/components/educationIntro/EducationIntro.module.scss
  src/pages/education/components/educationReview/EducationReview.module.scss
  src/pages/education/components/educationSystem/EducationSystem.module.scss
  src/pages/education/components/educationTitle/EducationTitle.module.scss
Labels: 🎨 Design

#76 Feat : 메인 페이지 비주얼 섹션
  package.json
  public/gendata.png
  public/index.html
  src/assets/main/back.jpg
  src/pages/main/components/background/Background.js
  src/pages/main/components/background/Background.module.scss
  src/pages/main/components/background/Content.js
  src/pages/main/components/background/Content.module.scss
  src/pages/main/components/background/Iframe.module.scss
  src/pages/main/components/clients/owlStyle/_animate.scss
  src/pages/main/components/clients/owlStyle/_autoheight.scss
  src/pages/main/components/clients/owlStyle/_core.scss
  src/pages/main/components/clients/owlStyle/_lazyload.scss
  src/pages/main/components/clients/owlStyle/_theme.default.scss
  src/pages/main/components/clients/owlStyle/_theme.green.scss
  src/pages/main/components/clients/owlStyle/_theme.scss
  src/pages/main/components/clients/owlStyle/_video.scss
  src/pages/main/components/clients/owlStyle/owl.carousel.scss
  src/pages/main/components/clients/owlStyle/owl.theme.default.scss
  src/pages/main/components/clients/owlStyle/owl.theme.green.scss
  yarn.lock
Labels: ✨ Feat

#77 Choir : 라이브러리 변경 떄문
  package.json
  yarn.lock
Labels: ⚙️ Chore

#78 Design/heekyung/ai develop
  src/pages/ai-development/components/AiDevelopmentApplication.module.scss
  src/pages/ai-development/components/AiDevelopmentRecommend.module.scss
Labels: 🎨 Design

#55 Feat: animaion css 코드 작성
  src/components/common/animation/FadeIn.scss
  src/components/common/animation/FadeInUp.scss
Labels: ✨ Feat

#79 Design/heekyung/news
  src/Mock/newsBoard.json
  src/pages/news/components/newsBoard/NewsBoard.module.scss
  src/pages/news/components/newsBoard/components/NewsBoardList.module.scss
  src/pages/news/components/newsBoardTitle/NewsBoardTitle.js
  src/pages/news/components/newsBoardTitle/NewsBoardTitle.module.scss
Labels: ⚙️ Chore, 🎨 Design

#80 Fix: 회사소개 페이지 반응형 개발 및 수정
  src/assets/about/accessible.png
  src/assets/about/corevalue.png
  src/assets/about/history_2021_mobile.png
  src/assets/about/history_2022_mobile.png
  src/assets/about/history_2023_mobile.png
  src/assets/about/info.png
  src/assets/about/mission.png
  src/assets/about/ourMission.png
  src/assets/about/ourVision.png
  src/pages/about/About.js
  src/pages/about/components/Contact.js
  src/pages/about/components/WidgetSection.js
  src/pages/about/components/aboutHeader.js
  src/pages/about/components/aboutHisory.js
  src/pages/about/components/aboutIntro.js
  src/pages/about/components/aboutSection.js
  src/pages/about/components/aboutSectionThree.js
  src/pages/about/components/aboutSectionTwo.js
  src/pages/about/components/scss/Contact.module.scss
  src/pages/about/components/scss/WidgetSection.module.scss
  src/pages/about/components/scss/aboutHeader.module.scss
  src/pages/about/components/scss/aboutHistory.module.scss
  src/pages/about/components/scss/aboutIntro.module.scss
  src/pages/about/components/scss/aboutSection.module.scss
  src/pages/about/components/scss/aboutSectionThree.module.scss
  src/pages/about/components/scss/aboutSectionTwo.module.scss
  src/pages/main/components/background/Iframe.js
  src/pages/main/components/clients/Swipe.js
  src/style/style.scss
Labels: 🚜 Refactor, 🛠 Fix, ✨ Feat, 🎨 Design

#83 Feat : 메인 비지니스 부터 문의하기 섹션 구현
  src/assets/main/bottom_banner.png
  src/assets/main/bottom_banner_logo1.png
  src/assets/main/bottom_banner_small.png
  src/pages/main/Main.js
  src/pages/main/components/MainContact/MainContact.js
  src/pages/main/components/MainContact/MainContact.module.scss
  src/pages/main/components/bottom-banner/BottomBanner.js
  src/pages/main/components/bottom-banner/BottomBanner.module.scss
  src/pages/main/components/business/Business.module.scss
Labels: ✨ Feat

#85 Feat : 메인 페이지 Clients 슬라이드와 탭 구현
  src/components/common/button-type/ButtonType.module.scss
  src/components/common/tab-module/Tab.module.scss
  src/components/common/tab-module/TabContent.module.scss
  src/pages/about/About.js
  src/pages/main/components/background/Background.module.scss
  src/pages/main/components/background/Content.js
  src/pages/main/components/background/Content.module.scss
  src/pages/main/components/buildingData/BuildingData.module.scss
  src/pages/main/components/clients/AiTitle.module.scss
  src/pages/main/components/clients/AutoSlider.module.scss
  src/pages/main/components/clients/Clients.js
  src/pages/main/components/clients/Clients.module.scss
Labels: ✨ Feat

#86 Feature/heekyung/main/issue and security
  src/assets/issueAndSecurity/1.png
  src/assets/issueAndSecurity/2.png
  src/assets/issueAndSecurity/3.png
  src/assets/issueAndSecurity/4.png
  src/assets/nextButton.png
  src/assets/prevButton.png
  src/pages/main/Main.js
  src/pages/main/components/issueAndSecurity/ClickSlider.js
  src/pages/main/components/issueAndSecurity/ClickSlider.module.scss
  src/pages/main/components/issueAndSecurity/ImgArr.js
  src/pages/main/components/issueAndSecurity/IssueAndSecurity.js
  src/pages/main/components/issueAndSecurity/IssueAndSecurity.module.scss
Labels: ✨ Feat, ⚙️ Chore, 🎨 Design

#88 Refactor: 햄버거 버튼 색 수정 및 Gnb 리렌더링 문제 개선
  src/components/gnb/Gnb.js
  src/components/gnb/Gnb.module.scss
Labels: 🚜 Refactor, 🎨 Design

#89 Feat : 메인 세모Ai 섹션 구현
  src/assets/main/banner1.png
  src/assets/main/banner2.png
  src/assets/main/banner3.png
  src/assets/main/banner4.png
  src/assets/main/banner5.png
  src/assets/main/man.png
  src/assets/main/next.png
  src/assets/main/prev.png
  src/assets/main/semoAiBanner.png
  src/assets/main/semoAiBannerSmall.png
  src/pages/main/components/semoAi/ClickSlider.js
  src/pages/main/components/semoAi/ClickSlider.module.scss
  src/pages/main/components/semoAi/ImgArr.js
  src/pages/main/components/semoAi/SemoAi.js
  src/pages/main/components/semoAi/SemoAi.module.scss
  src/pages/main/components/semoAi/SemoAiMobile.js
  src/pages/main/components/semoAi/SemoAiMobile.module.scss
  src/pages/main/components/semoAi/SemoAiPc.js
  src/pages/main/components/semoAi/SemoAiPc.module.scss
Labels: ✨ Feat

#87 Fix/heekyung/detail
  src/components/common/typo/Typo.module.scss
  src/components/contact-button/ContactButton.js
  src/components/contact-button/ContactButton.module.scss
  src/components/footer/Footer.module.scss
  src/components/strength/Strength.module.scss
  src/components/title/Title.module.scss
  src/pages/ai-development/components/AiDevelopmentApplication.module.scss
  src/pages/ai-development/components/AiDevelopmentCase.module.scss
  src/pages/ai-development/components/AiDevelopmentRecommend.module.scss
  src/pages/education/Education.js
  src/pages/education/components/educationIntro/EducationIntro.module.scss
  src/pages/education/components/educationReview/EducationReview.module.scss
  src/pages/education/components/educationSystem/EducationSystem.module.scss
  src/pages/education/components/educationTitle/EducationTitle.module.scss
  src/pages/news/components/newsBoard/NewsBoard.module.scss
  src/pages/news/components/newsBoard/components/NewsBoardList.module.scss
  src/pages/news/components/newsBoardTitle/NewsBoardTitle.module.scss
Labels: 🛠 Fix, 🎨 Design

#90 Design/heekyung/news
  src/pages/news/components/newsBoardTitle/NewsBoardTitle.js
  src/pages/newsContents/NewsContents.js
  src/pages/newsContents/NewsContents.module.scss
Labels: 🎨 Design, ✨ Style

#91 Design: 데이터 가공 반응형 css 수정
  src/pages/data-dealing/components/DataDealingBanner.js
  src/pages/data-dealing/components/DataDealingBanner.module.scss
  src/pages/data-dealing/components/DataDealingTitle.js
  src/pages/data-dealing/components/DataDealingTypes.module.scss
Labels: 🎨 Design

#92 Feat: Helmet title 적용
  package.json
  public/index.html
  src/index.js
  src/pages/about/About.js
  src/pages/about/components/AboutHisory.js
  src/pages/ai-development/AiDevelopment.js
  src/pages/ai-service/AiService.js
  src/pages/contact/Contact.js
  src/pages/data-dealing/DataDealing.js
  src/pages/education/Education.js
  src/pages/government/Government.js
  src/pages/main/Main.js
  src/pages/news/News.js
  src/pages/project-develop/Project.js
  src/pages/service-labeling/DataCollection.js
  src/pages/service-labeling/DataProcess3d.js
  src/pages/service-labeling/DataProcessAudio.js
  src/pages/service-labeling/DataProcessText.js
  src/pages/service-labeling/DataProcessVideo.js
  src/pages/service-labeling/InHouseOperation.js
  src/pages/service-labeling/ServiceLabeling.js
  yarn.lock
Labels: ✨ Feat

#93 Fix/heekyung/detail 파일 이름으로 인한 경로 문제 해결
  src/pages/about/components/aboutHeader.js
  src/pages/about/components/aboutHistoryButton.js
  src/pages/about/components/aboutSection.js
  src/pages/about/components/aboutSectionThree.js
  src/pages/about/components/aboutSectionTwo.js
  src/pages/about/components/scss/aboutHistory.module.scss
  src/pages/about/components/scss/aboutSection.module.scss
  src/pages/about/components/scss/aboutSectionTwo.module.scss
Labels: 🛠 Fix

#94 Feat : 메인 페이지 슬라이드 구현
  src/assets/main/next.png
  src/assets/main/prev.png
  src/assets/main/whiteButtn.png
  src/assets/main/whiteButtnL.png
  src/components/common/button-type/ButtonType.module.scss
  src/pages/main/components/background/Content.module.scss
  src/pages/main/components/issueAndSecurity/ClickSlider.js
  src/pages/main/components/issueAndSecurity/ClickSlider.module.scss
  src/pages/main/components/issueAndSecurity/IssueAndSecurity.js
  src/pages/main/components/issueAndSecurity/IssueAndSecurity.module.scss
  src/pages/main/components/semoAi/ClickSlider.js
  src/pages/main/components/semoAi/ClickSlider.module.scss
Labels: ✨ Feat
